//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.4.2+b87d519
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "featureSettingsComponentItemsPropertiesSlideshow"
	/// <summary>Feature Settings Component - Items Properties - Slideshow</summary>
	public partial interface IFeatureSettingsComponentItemsPropertiesSlideshow : IPublishedElement
	{
		/// <summary>Show Slide Count</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		bool ShowSlideCount { get; }

		/// <summary>Show Slide Pips</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		bool ShowSlidePips { get; }
	}

	/// <summary>Feature Settings Component - Items Properties - Slideshow</summary>
	[PublishedModel("featureSettingsComponentItemsPropertiesSlideshow")]
	public partial class FeatureSettingsComponentItemsPropertiesSlideshow : PublishedElementModel, IFeatureSettingsComponentItemsPropertiesSlideshow
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const string ModelTypeAlias = "featureSettingsComponentItemsPropertiesSlideshow";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<FeatureSettingsComponentItemsPropertiesSlideshow, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public FeatureSettingsComponentItemsPropertiesSlideshow(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Show Slide Count: Turn on to show the slide counter (e.g. 1 of 12), off to hide.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("showSlideCount")]
		public virtual bool ShowSlideCount => GetShowSlideCount(this, _publishedValueFallback);

		/// <summary>Static getter for Show Slide Count</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public static bool GetShowSlideCount(IFeatureSettingsComponentItemsPropertiesSlideshow that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "showSlideCount");

		///<summary>
		/// Show Slide Pips: Turn on to show the indicator dots, off to hide.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("showSlidePips")]
		public virtual bool ShowSlidePips => GetShowSlidePips(this, _publishedValueFallback);

		/// <summary>Static getter for Show Slide Pips</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public static bool GetShowSlidePips(IFeatureSettingsComponentItemsPropertiesSlideshow that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "showSlidePips");
	}
}
