//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.4.2+b87d519
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Feature Settings - Internal Links</summary>
	[PublishedModel("featureSettingsInternalLinks")]
	public partial class FeatureSettingsInternalLinks : PublishedElementModel, IFeatureSettingsComponentHideDisplay, IFeatureSettingsComponentItemsLayout, IFeatureSettingsComponentItemsProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const string ModelTypeAlias = "featureSettingsInternalLinks";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<FeatureSettingsInternalLinks, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public FeatureSettingsInternalLinks(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Hide or Display: Turn on to display or off to hide. Displayed is on by default.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("featureSettingsHideDisplay")]
		public virtual bool FeatureSettingsHideDisplay => global::Umbraco.Cms.Web.Common.PublishedModels.FeatureSettingsComponentHideDisplay.GetFeatureSettingsHideDisplay(this, _publishedValueFallback);

		///<summary>
		/// Columns: The number of columns when the viewport is at its widest. Narrower screens step down automatically.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("itemsLayoutColumns")]
		public virtual string ItemsLayoutColumns => global::Umbraco.Cms.Web.Common.PublishedModels.FeatureSettingsComponentItemsLayout.GetItemsLayoutColumns(this, _publishedValueFallback);

		///<summary>
		/// Show Item Descriptions: Turn on to show each item's description, off to hide.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("showItemDescriptions")]
		public virtual bool ShowItemDescriptions => global::Umbraco.Cms.Web.Common.PublishedModels.FeatureSettingsComponentItemsProperties.GetShowItemDescriptions(this, _publishedValueFallback);

		///<summary>
		/// Show Item Titles: Turn on to show each item's title, off to hide.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("showItemTitles")]
		public virtual bool ShowItemTitles => global::Umbraco.Cms.Web.Common.PublishedModels.FeatureSettingsComponentItemsProperties.GetShowItemTitles(this, _publishedValueFallback);
	}
}
