//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.4.2+b87d519
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Image - Responsive</summary>
	[PublishedModel("imageResponsive")]
	public partial class ImageResponsive : PublishedContentModel, IMediaComponentDestinations, IMediaComponentImageAssetId, IMediaComponentImageCopyright, IMediaComponentImageCreator, IMediaComponentImageMetadata, IMediaComponentImageSourceFilename, IMediaComponentImageSupplier, IMediaComponentMetadata
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const string ModelTypeAlias = "imageResponsive";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<ImageResponsive, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ImageResponsive(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Size: in bytes
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("umbracoBytes")]
		public virtual long UmbracoBytes => this.Value<long>(_publishedValueFallback, "umbracoBytes");

		///<summary>
		/// Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoExtension")]
		public virtual string UmbracoExtension => this.Value<string>(_publishedValueFallback, "umbracoExtension");

		///<summary>
		/// Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("umbracoFile")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ImageCropperValue UmbracoFile => this.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ImageCropperValue>(_publishedValueFallback, "umbracoFile");

		///<summary>
		/// Height: in pixels
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("umbracoHeight")]
		public virtual int UmbracoHeight => this.Value<int>(_publishedValueFallback, "umbracoHeight");

		///<summary>
		/// Width: in pixels
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("umbracoWidth")]
		public virtual int UmbracoWidth => this.Value<int>(_publishedValueFallback, "umbracoWidth");

		///<summary>
		/// Country: Which country is the subject of the image in
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyCountry")]
		public virtual string MediaPropertyCountry => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentDestinations.GetMediaPropertyCountry(this, _publishedValueFallback);

		///<summary>
		/// Regions: To help categorisation in the back office you can add multiple categories but at least one must match a Group Tours destination and should appear first in the list e.g. Krakow = central-and-eastern-europe, poland
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyRegions")]
		public virtual global::System.Collections.Generic.IEnumerable<string> MediaPropertyRegions => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentDestinations.GetMediaPropertyRegions(this, _publishedValueFallback);

		///<summary>
		/// Asset ID: The ID provided by the supplier of the image e.g. iStock ID
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyImageAssetId")]
		public virtual string MediaPropertyImageAssetId => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentImageAssetId.GetMediaPropertyImageAssetId(this, _publishedValueFallback);

		///<summary>
		/// Copyright: The Copyright for this image. No need to add ©.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyImageCopyright")]
		public virtual string MediaPropertyImageCopyright => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentImageCopyright.GetMediaPropertyImageCopyright(this, _publishedValueFallback);

		///<summary>
		/// Creator: The creator of the image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyImageCreator")]
		public virtual string MediaPropertyImageCreator => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentImageCreator.GetMediaPropertyImageCreator(this, _publishedValueFallback);

		///<summary>
		/// Alt Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyAltText")]
		public virtual string MediaPropertyAltText => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentImageMetadata.GetMediaPropertyAltText(this, _publishedValueFallback);

		///<summary>
		/// Filename: The filename of the image as supplied, though spaces, capitals and special characters may have been simplified on upload.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyImageSourceFilename")]
		public virtual string MediaPropertyImageSourceFilename => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentImageSourceFilename.GetMediaPropertyImageSourceFilename(this, _publishedValueFallback);

		///<summary>
		/// Supplier: The name of the supplier of the image e.g. Shutterstock, iStock, Getty
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyImageSupplier")]
		public virtual global::System.Collections.Generic.IEnumerable<string> MediaPropertyImageSupplier => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentImageSupplier.GetMediaPropertyImageSupplier(this, _publishedValueFallback);

		///<summary>
		/// Description 
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyDescription")]
		public virtual string MediaPropertyDescription => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentMetadata.GetMediaPropertyDescription(this, _publishedValueFallback);

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mediaPropertyTitle")]
		public virtual string MediaPropertyTitle => global::Umbraco.Cms.Web.Common.PublishedModels.MediaComponentMetadata.GetMediaPropertyTitle(this, _publishedValueFallback);
	}
}
