//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.4.2+b87d519
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Individual Tour</summary>
	[PublishedModel("individualTour")]
	public partial class IndividualTour : PublishedContentModel, IContentGridIndividualTour, IContentHeadingDefault, IContentHeadingDefault1, IPageComponentTourDepartureDate, IPageComponentTourDuration, IPageComponentTourPrice, ITourBrochure, ITourDestinations, ITourOrganisers
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const string ModelTypeAlias = "individualTour";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<IndividualTour, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public IndividualTour(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Block Grid Individual Tour: Hover 'Block Grid Editor' then click the 3 dots to switch to Sort Mode (a simplified view for rearranging the page). The Block Grid Editor allows you to add Layout Blocks consisting of one or more Areas which in turn may contain Feature Blocks such as Text or Images
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("blockGridIndividualTour")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel BlockGridIndividualTour => global::Umbraco.Cms.Web.Common.PublishedModels.ContentGridIndividualTour.GetBlockGridIndividualTour(this, _publishedValueFallback);

		///<summary>
		/// Page Description: This will appear in pages
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageDescription")]
		public virtual string PageDescription => global::Umbraco.Cms.Web.Common.PublishedModels.ContentHeadingDefault.GetPageDescription(this, _publishedValueFallback);

		///<summary>
		/// Page Thumbnail: This will appear in navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageThumbnail")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops PageThumbnail => global::Umbraco.Cms.Web.Common.PublishedModels.ContentHeadingDefault.GetPageThumbnail(this, _publishedValueFallback);

		///<summary>
		/// Page Title: This will appear in pages
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => global::Umbraco.Cms.Web.Common.PublishedModels.ContentHeadingDefault.GetPageTitle(this, _publishedValueFallback);

		///<summary>
		/// Page Title Short: This will appear in navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitleShort")]
		public virtual string PageTitleShort => global::Umbraco.Cms.Web.Common.PublishedModels.ContentHeadingDefault.GetPageTitleShort(this, _publishedValueFallback);

		///<summary>
		/// Page Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageSettingsBackgroundImagePicker")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops PageSettingsBackgroundImagePicker => global::Umbraco.Cms.Web.Common.PublishedModels.ContentHeadingDefault1.GetPageSettingsBackgroundImagePicker(this, _publishedValueFallback);

		///<summary>
		/// Skybrud Redirects: These are redirects from the old URLs that have been added using the Skybrud Redirects Plugin
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("redirects")]
		public virtual string Redirects => global::Umbraco.Cms.Web.Common.PublishedModels.ContentHeadingDefault1.GetRedirects(this, _publishedValueFallback);

		///<summary>
		/// Tour Departure Date: The date this tour departs
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("pagePropertyTourDepartureDate")]
		public virtual global::System.Nullable<global::System.DateOnly> PagePropertyTourDepartureDate => global::Umbraco.Cms.Web.Common.PublishedModels.PageComponentTourDepartureDate.GetPagePropertyTourDepartureDate(this, _publishedValueFallback);

		///<summary>
		/// Tour Duration: Number of days
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("pagePropertyTourDuration")]
		public virtual int PagePropertyTourDuration => global::Umbraco.Cms.Web.Common.PublishedModels.PageComponentTourDuration.GetPagePropertyTourDuration(this, _publishedValueFallback);

		///<summary>
		/// Tour Price (from): The starting price for this tour
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("pagePropertyTourPriceFrom")]
		public virtual int PagePropertyTourPriceFrom => global::Umbraco.Cms.Web.Common.PublishedModels.PageComponentTourPrice.GetPagePropertyTourPriceFrom(this, _publishedValueFallback);

		///<summary>
		/// Brochure PDF
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("brochurePdf")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BrochurePdf => global::Umbraco.Cms.Web.Common.PublishedModels.TourBrochure.GetBrochurePdf(this, _publishedValueFallback);

		///<summary>
		/// Destinations: Destinations that this tour visits
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("destinations")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent> Destinations => global::Umbraco.Cms.Web.Common.PublishedModels.TourDestinations.GetDestinations(this, _publishedValueFallback);

		///<summary>
		/// Organisers
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("organisers")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Organisers => global::Umbraco.Cms.Web.Common.PublishedModels.TourOrganisers.GetOrganisers(this, _publishedValueFallback);
	}
}
