//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.4.2+b87d519
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Layout Settings 8</summary>
	[PublishedModel("layoutSettings8")]
	public partial class LayoutSettings8 : PublishedElementModel, ILayoutSettingsComponentAreasBorderColourPrimary, ILayoutSettingsComponentAreasBorderWidthPrimary, ILayoutSettingsComponentAreasColorPrimary, ILayoutSettingsComponentBackgroundImage, ILayoutSettingsComponentColorPicker
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const string ModelTypeAlias = "layoutSettings8";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<LayoutSettings8, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public LayoutSettings8(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Primary Area Border Colour
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layoutPrimaryAreaBorderColour")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor LayoutPrimaryAreaBorderColour => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentAreasBorderColourPrimary.GetLayoutPrimaryAreaBorderColour(this, _publishedValueFallback);

		///<summary>
		/// Primary Area Border Width
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("layoutPrimaryAreaBorderWidth")]
		public virtual decimal LayoutPrimaryAreaBorderWidth => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentAreasBorderWidthPrimary.GetLayoutPrimaryAreaBorderWidth(this, _publishedValueFallback);

		///<summary>
		/// Primary Background Colour
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layoutPrimaryAreaColour")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor LayoutPrimaryAreaColour => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentAreasColorPrimary.GetLayoutPrimaryAreaColour(this, _publishedValueFallback);

		///<summary>
		/// Layout Settings Background Image Picker
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layoutSettingsBackgroundImagePicker")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LayoutSettingsBackgroundImagePicker => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentBackgroundImage.GetLayoutSettingsBackgroundImagePicker(this, _publishedValueFallback);

		///<summary>
		/// Opacity
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("layoutSettingsColourOpacity")]
		public virtual decimal LayoutSettingsColourOpacity => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentColorPicker.GetLayoutSettingsColourOpacity(this, _publishedValueFallback);

		///<summary>
		/// Colour
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layoutSettingsColourPicker")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor LayoutSettingsColourPicker => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentColorPicker.GetLayoutSettingsColourPicker(this, _publishedValueFallback);

		///<summary>
		/// Shade
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("layoutSettingsColourShades")]
		public virtual decimal LayoutSettingsColourShades => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutSettingsComponentColorPicker.GetLayoutSettingsColourShades(this, _publishedValueFallback);
	}
}
