//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.4.2+b87d519
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "layoutSettingsComponentAreasBorderWidthSecondary"
	/// <summary>Layout Settings Component - Areas Border Width - Secondary</summary>
	public partial interface ILayoutSettingsComponentAreasBorderWidthSecondary : IPublishedElement
	{
		/// <summary>Secondary Area Border Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		decimal LayoutSecondaryAreaBorderWidth { get; }
	}

	/// <summary>Layout Settings Component - Areas Border Width - Secondary</summary>
	[PublishedModel("layoutSettingsComponentAreasBorderWidthSecondary")]
	public partial class LayoutSettingsComponentAreasBorderWidthSecondary : PublishedElementModel, ILayoutSettingsComponentAreasBorderWidthSecondary
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const string ModelTypeAlias = "layoutSettingsComponentAreasBorderWidthSecondary";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<LayoutSettingsComponentAreasBorderWidthSecondary, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public LayoutSettingsComponentAreasBorderWidthSecondary(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Secondary Area Border Width
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		[ImplementPropertyType("layoutSecondaryAreaBorderWidth")]
		public virtual decimal LayoutSecondaryAreaBorderWidth => GetLayoutSecondaryAreaBorderWidth(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Area Border Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.4.2+b87d519")]
		public static decimal GetLayoutSecondaryAreaBorderWidth(ILayoutSettingsComponentAreasBorderWidthSecondary that, IPublishedValueFallback publishedValueFallback) => that.Value<decimal>(publishedValueFallback, "layoutSecondaryAreaBorderWidth");
	}
}
